// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eraetbzzdfomzntuikhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYWV0Ynp6ZGZvbXpudHVpa2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODczNjAsImV4cCI6MjA3MDE2MzM2MH0.zl310brJbPmmxNV3LPg5cRXvw6or7UW6M5BrW7p-R80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});